name: CI Node broken ?
on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-13, ubuntu-22.04]
        node: [21.1.0, 21.2.0, 22.16.0]
    runs-on: ${{ matrix.os }}
    steps:
      - name: update os
        run: sudo apt-get update && sudo apt-get upgrade -y
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: show node options
        run: node --print-flag-values --v8-options|grep wasm
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Test
        run: pnpm test
