name: 21.2.0
on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, windows-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.2.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: show node options
        run: node --print-flag-values|grep wasm
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Test
        run: pnpm test
