name: 20.19.4
on: workflow_dispatch

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, windows-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install
        run: pnpm install --frozen-lockfile=false
      - name: Test
        run: pnpm test
